version: '3.3'
services:
  db:
     container_name: 'dsn-wp-db'
     image: mysql:5.7
     volumes:
       - "./data/mysql:/var/lib/mysql"
     ports:
       - 18766:3306
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  wordpress:
     container_name: 'dsn-wp'
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - "./plugins:/var/www/html/wp-content/plugins"
